"""Renderer Contract v1 infrastructure.

This package intentionally contains no renderer, V4 mapper, provider access or
media execution code.
"""

from .canonical import (
    CanonicalizationError,
    canonical_json_bytes,
    canonical_json_text,
    canonical_sha256,
    request_id_from_hash,
    semantic_request_hash,
    semantic_snapshot_hash,
    snapshot_id_from_hash,
)
from .enums import (
    CaptionTimingLevel,
    PathRootKind,
    RenderMode,
    RendererCapability,
    RendererErrorCode,
    RenderStatus,
    TimelineAssetKind,
)
from .errors import ContractValidationError, RenderIssue, SnapshotWriteError
from .models import (
    ArtifactBinding,
    CapabilityDefinition,
    PortableRef,
    ProfileBinding,
    ProjectBinding,
    ReleaseBinding,
    ReleaseSnapshot,
    RenderRequest,
    RendererCapabilities,
    RendererIdentity,
    RenderResult,
)
from .paths import PortablePathError, RootResolver, normalize_portable_path
from .release_snapshot import (
    create_release_snapshot,
    snapshot_filename,
    write_release_snapshot,
)
from .serialization import (
    capabilities_from_dict,
    capabilities_to_dict,
    release_snapshot_from_dict,
    release_snapshot_to_dict,
    render_request_from_dict,
    render_request_to_dict,
    render_result_from_dict,
    render_result_to_dict,
)
from .validation import (
    compare_capabilities,
    stable_issues,
    validate_capabilities,
    validate_extensions,
    validate_gate_rights,
    validate_release_snapshot,
    validate_render_request,
    validate_render_result,
    validate_request_filesystem,
    validate_request_capabilities,
    validate_request_hash,
    validate_snapshot_hash,
)

__all__ = [
    "ArtifactBinding",
    "CanonicalizationError",
    "CaptionTimingLevel",
    "CapabilityDefinition",
    "ContractValidationError",
    "PathRootKind",
    "PortablePathError",
    "PortableRef",
    "ProfileBinding",
    "ProjectBinding",
    "ReleaseBinding",
    "ReleaseSnapshot",
    "RenderIssue",
    "RenderMode",
    "RenderRequest",
    "RenderResult",
    "RendererCapabilities",
    "RendererCapability",
    "RendererErrorCode",
    "RendererIdentity",
    "RenderStatus",
    "RootResolver",
    "SnapshotWriteError",
    "TimelineAssetKind",
    "canonical_json_bytes",
    "canonical_json_text",
    "canonical_sha256",
    "capabilities_from_dict",
    "capabilities_to_dict",
    "compare_capabilities",
    "create_release_snapshot",
    "normalize_portable_path",
    "release_snapshot_from_dict",
    "release_snapshot_to_dict",
    "render_request_from_dict",
    "render_request_to_dict",
    "render_result_from_dict",
    "render_result_to_dict",
    "request_id_from_hash",
    "semantic_request_hash",
    "semantic_snapshot_hash",
    "snapshot_filename",
    "snapshot_id_from_hash",
    "stable_issues",
    "validate_capabilities",
    "validate_extensions",
    "validate_gate_rights",
    "validate_release_snapshot",
    "validate_render_request",
    "validate_render_result",
    "validate_request_filesystem",
    "validate_request_capabilities",
    "validate_request_hash",
    "validate_snapshot_hash",
    "write_release_snapshot",
]
